input_col_map = {
  'LBXMCHSI': 'MCH',
  'LBDLYMNO': 'Lymphs (Absolute)',
  'RIDAGEYR': 'PATIENT_AGE_YEARS',
  'LBXPLTSI': 'Platelets',
  'LBDMONO': 'Monocytes(Absolute)',
  'LBXSGB': 'Globulin, Total',
  'LBXRDW': 'RDW',
  #'LBXTR': 'Triglycerides',
  'LBXSTR': 'Triglycerides',
  #'LB2STR': 'Triglycerides',
  #'LB2TR': 'Triglycerides',
  'LBXFER': 'Ferritin, Serum',
  'LB2FER': 'Ferritin, Serum',
  'LBDFER': 'Ferritin, Serum',
  'LBXTIB': 'Iron Bind.Cap.(TIBC)',
  'LBDTIB': 'Iron Bind.Cap.(TIBC)',
  'LBDEONO': 'Eos (Absolute)',
  'LBDBANO': 'Baso (Absolute)',
  'LBXSAL': 'Albumin, Serum',
  'LBXSCR': 'Creatinine, Serum',
  'LBDSCR': 'Creatinine, Serum',
  'LBXSPH': 'Phosphorus, Serum',
  'LBDSPH': 'Phosphorus, Serum',
  'LBDNENO': 'Neutrophils (Absolute)',
  'LBXSGL': 'Glucose, Serum',
  'LBXTC': 'Cholesterol, Total',
  'LBXSIR': 'Iron, Serum',
  'LBXSCA': 'Calcium, Serum',
  'LBXSCLSI': 'Chloride, Serum',
  'LBXSLDSI': 'LDH',
  'LB2SLDSI': 'LDH',
  'LBXSBU': 'BUN',
  'LBXSASSI': 'AST (SGOT)',
  'LBXSATSI': 'ALT (SGPT)',
  'LBXSTB': 'Bilirubin, Total',
  'LB2STB': 'Bilirubin, Total',
  'LBXSNASI': 'Sodium, Serum',
  'LBXSUA': 'Uric Acid, Serum',
  'LBXSAPSI': 'Alkaline Phosphatase, S',
  'LBDSAPSI':  'Alkaline Phosphatase, S',
  'LBXSGTSI': 'GGT',
  'LBXSC3SI': 'Carbon Dioxide, Total',
  'LBDHDD': 'HDL-C',
  'LBDHDL': 'HDL-C',
  'LBXHDD': 'HDL-C',
  'LBXHCT': 'Hematocrit',
  'LBXSKSI': 'Potassium, Serum',
  'LBXMC': 'MCHC',
  'LBXMCVSI': 'MCV',
  'RIAGENDR': 'PATIENT_GNDR',
  'LBXRBCSI': 'RBC',
  'LBXHGB': 'Hemoglobin',
  'LBDLDL': 'LDL-C',
  'LBXMPSI': 'MPV',
}
included_markers = input_col_map.values()

output_col_map = {
    'YEAR': 'YEAR',
}

all_cols = set(output_col_map.keys()) | set(input_col_map.keys())
